---
apiVersion: v1
kind: ConfigMap
metadata:
  name: a10-opa-policy-config
  namespace: policy
data:
  config.yaml: |+
    ## Debug level 0 -> 10
    debug: 10
    ## OPA Node info
    OPA_IP: 10.1.1.220
    OPA_PORT: 30181
    ## Thunder ADC Node info
    THND_IP: 10.1.1.33
    THND_PORT: 443
    THND_USER: admin
    THND_PASSWD: a10
    THND_ID: thunder-1
    # yaml array, but Unmarshalled as JSON...yes, it works :)
    vs: [
      {"name": "ws-vip", "policy": "bw"},
      {"name": "ws-vip", "policy": "cps"}
    ]
    # CHECK_INTERVAL is in seconds.
    CHECK_INTERVAL: 120
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a10-opa-proxy
  namespace: policy
  labels:
    app: a10-opa-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a10-opa-proxy
  template:
    metadata:
      labels:
        app: a10-opa-proxy
      name: a10-opa-proxy
    spec:
      containers:
      - name: a10-opa-proxy
        image: 10.1.1.30:5000/a10-opa-proxy:latest
        volumeMounts:
          - name: a10-opa-policy-config
            mountPath: /config/config.yaml
            subPath: config.yaml
            readOnly: true
      volumes:
      - name: a10-opa-policy-config
        configMap:
          name: a10-opa-policy-config
          items:
          - key: config.yaml
            path: config.yaml  
